In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [3]:
tf.constant([1.,2.,3.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [3]:
t = tf.constant([1.,2.,3.])
t.shape

TensorShape([3])

In [5]:
t[1]

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [6]:
t * 10

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>

In [8]:
tf.add(t,10) == t + 10

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True,  True,  True])>

خیلی از عملیات هایی که بر روی آرایه های نامپای انجام می دادیم قابل انجام بر روی 

In [10]:
np.log(t)

array([0.       , 0.6931472, 1.0986123], dtype=float32)

In [12]:
tf.math.log(t)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.       , 0.6931472, 1.0986123], dtype=float32)>

In [5]:
t1 = tf.constant(np.random.randint(1,100,size =(8,4)))

tf.transpose(t1)

<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[43, 19, 61, 47, 65, 58, 91, 28],
       [15, 52, 34, 89, 84, 48, 31, 10],
       [ 3, 64, 29, 37, 36, 60, 59, 19],
       [99, 60, 80, 47, 41, 29, 24, 50]])>

In [6]:
tf.reduce_mean(t1)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

In [7]:
t2 = tf.constant(np.random.random(size = (8,4)))

t2

<tf.Tensor: shape=(8, 4), dtype=float64, numpy=
array([[0.54920939, 0.84611303, 0.51381196, 0.99101808],
       [0.39406766, 0.10519764, 0.61048462, 0.81640554],
       [0.00485425, 0.93922568, 0.97765023, 0.61918426],
       [0.34087963, 0.00470771, 0.86108132, 0.19896313],
       [0.78617614, 0.35816229, 0.09360071, 0.79159521],
       [0.10187566, 0.69525776, 0.36789498, 0.38464591],
       [0.87397999, 0.8282145 , 0.79188966, 0.05027123],
       [0.43743074, 0.41862218, 0.90539152, 0.1915562 ]])>

Notice that NumPy uses 64-bit precision by default, while TensorFlow uses 32-bit.
This is because 32-bit precision is generally more than enough for neural networks,
plus it runs faster and uses less RAM. So when you create a tensor from a NumPy
array, make sure to set dtype=tf.float32.

In [8]:
t2 = tf.constant(np.random.random(size = (8,4)),dtype=tf.float32)

t2

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[9.8267597e-01, 2.5016123e-01, 1.9255697e-03, 7.0434654e-01],
       [5.3759676e-01, 2.9489803e-01, 5.9103966e-01, 8.2506627e-01],
       [3.7561673e-01, 5.9319854e-01, 3.7370005e-01, 1.9675912e-01],
       [1.1899771e-02, 6.0247775e-04, 4.6007913e-01, 7.7466363e-01],
       [9.3221462e-01, 4.7079861e-01, 2.7181885e-01, 3.5269183e-01],
       [3.5358980e-01, 3.3599868e-02, 2.1656312e-01, 8.1383026e-01],
       [6.0913169e-01, 5.6409359e-01, 7.3491746e-01, 3.1678292e-01],
       [4.9082589e-01, 3.6050871e-01, 1.0644488e-01, 8.2004571e-01]],
      dtype=float32)>

Type Conversion

In [11]:
t1 + t2

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]