In [3]:
### تعبیه سازی برای متغیرهای دسته ای
from palmerpenguins.penguins import load_penguins
from tensorflow.keras.layers import Subtract,Dense,Input,Concatenate
import pandas as pd
import tensorflow as tf
import numpy as np

In [4]:
ubaar = pd.read_csv('../data/train.csv')
ubaar.head()

ID    date  sourceLatitude  sourceLongitude         SourceState  \
0  88142929797  960218       36.666045        48.489706               زنجان   
1  30842979862  960511       32.323951        50.855412  چهارمحال و بختیاری   
2  54262798716  960602       32.575448        51.581011              اصفهان   
3  64071173752  960319       35.029685        48.085763             کردستان   
4  68088966447  960609       31.586965        54.449607                 یزد   

   destinationLatitude  destinationLongitude destinationState  distanceKM  \
0            29.600574             52.537114             فارس      1092.0   
1            34.644923             50.876092               قم       414.0   
2            31.819508             49.865235          خوزستان       310.0   
3            35.703801             51.398824            تهران       391.0   
4            36.730367             53.965480           گلستان       756.0   

   taxiDurationMin vehicleType    vehicleOption  weight     price  
0            751.0      treili             kafi   20.00  15300000  
1            264.0      khavar  mosaghaf_felezi    2.50   1800000  
2            292.0        joft        kompressi   14.97   3742000  
3            271.0      khavar  mosaghaf_felezi    2.50   1300000  
4            573.0        joft             bari   15.00   8870000

In [5]:
pd.unique(ubaar.SourceState)

array(['زنجان', 'چهارمحال و بختیاری', 'اصفهان', 'کردستان', 'یزد', 'کرمان',
       'تهران', 'فارس', 'سمنان', 'مرکزی', 'کرمانشاه', 'خراسان رضوی',
       'آذربایجان شرقی', 'لرستان', 'همدان', 'البرز', 'بوشهر', 'خوزستان',
       'سیستان و بلوچستان', 'قزوین', 'گلستان', 'مازندران', 'هرمزگان',
       'قم', 'آذربایجان غربی', 'اردبیل', 'گیلان', 'خراسان شمالی',
       'کهگیلویه و بویراحمد', 'خراسان جنوبی', 'ایلام'], dtype=object)

In [6]:
n_provinces = len(pd.unique(ubaar.SourceState))
n_provinces

31

### پیش پردازش داده ها

#### نبدیل متغییرهای دسته ای

In [8]:
ubaar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   ID                    50000 non-null  int64  
 1   date                  50000 non-null  int64  
 2   sourceLatitude        50000 non-null  float64
 3   sourceLongitude       50000 non-null  float64
 4   SourceState           50000 non-null  object 
 5   destinationLatitude   50000 non-null  float64
 6   destinationLongitude  50000 non-null  float64
 7   destinationState      50000 non-null  object 
 8   distanceKM            49997 non-null  float64
 9   taxiDurationMin       49997 non-null  float64
 10  vehicleType           50000 non-null  object 
 11  vehicleOption         50000 non-null  object 
 12  weight                50000 non-null  float64
 13  price                 50000 non-null  int64  
dtypes: float64(7), int64(3), object(4)
memory usage: 5.3+ MB


In [13]:
ubaar.drop('ID',axis = 1)

date  sourceLatitude  sourceLongitude         SourceState  \
0      960218       36.666045        48.489706               زنجان   
1      960511       32.323951        50.855412  چهارمحال و بختیاری   
2      960602       32.575448        51.581011              اصفهان   
3      960319       35.029685        48.085763             کردستان   
4      960609       31.586965        54.449607                 یزد   
...       ...             ...              ...                 ...   
49995  960308       32.178659        54.068647                 یزد   
49996  960130       33.990468        50.688987               مرکزی   
49997  960301       32.384790        48.406081             خوزستان   
49998  960122       34.795119        48.521234               همدان   
49999  960428       32.178747        54.062925                 یزد   

       destinationLatitude  destinationLongitude destinationState  distanceKM  \
0                29.600574             52.537114             فارس      1092.0   
1                34.644923             50.876092               قم       414.0   
2                31.819508             49.865235          خوزستان       310.0   
3                35.703801             51.398824            تهران       391.0   
4                36.730367             53.965480           گلستان       756.0   
...                    ...                   ...              ...         ...   
49995            32.675211             51.669889           اصفهان       291.0   
49996            35.695076             51.397359            تهران       252.0   
49997            33.989690             51.440449           اصفهان       554.0   
49998            35.705585             51.397401            تهران       323.0   
49999            36.294833             59.601507      خراسان رضوی       910.0   

       taxiDurationMin vehicleType    vehicleOption  weight     price  
0                751.0      treili             kafi   20.00  15300000  
1                264.0      khavar  mosaghaf_felezi    2.50   1800000  
2                292.0        joft        kompressi   14.97   3742000  
3                271.0      khavar  mosaghaf_felezi    2.50   1300000  
4                573.0        joft             bari   15.00   8870000  
...                ...         ...              ...     ...       ...  
49995            193.0      treili             kafi   23.89   6360000  
49996            179.0         tak        yakhchali    6.25   3255000  
49997            440.0      khavar  mosaghaf_felezi    4.50   6500000  
49998            226.0      khavar  mosaghaf_felezi    3.00   2600000  
49999            625.0      khavar  mosaghaf_felezi    1.00   5230000  

[50000 rows x 13 columns]

In [14]:

ubaar = pd.get_dummies(ubaar,columns=['SourceState','destinationState','vehicleType','vehicleOption'])

In [ ]:
#ubaar['']
#ubaar.drop('ID',axis = 1)

In [17]:
ubaar.dropna(inplace = True)

In [30]:
from sklearn.model_selection import train_test_split
X = ubaar.drop(['price'],axis = 1)
y = np.log(ubaar['price'])

X_train,X_test, y_train,y_test = train_test_split(X,y)

#### نرمال سازی داده ها

In [31]:
from sklearn.preprocessing import StandardScaler

ss  = StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)


In [33]:
X_train

array([[ 0.20365597,  0.19088286, -0.59146393, ..., -0.53177249,
        -0.24941505, -0.26652738],
       [ 0.5920366 , -1.56934396,  0.69663671, ..., -0.53177249,
        -0.24941505, -0.26652738],
       [-1.62036364,  0.78984893,  1.33485091, ...,  1.88050346,
        -0.24941505, -0.26652738],
       ...,
       [ 0.53792744,  1.49271728, -0.74470454, ..., -0.53177249,
        -0.24941505, -0.26652738],
       [-1.54336418, -1.53878447, -0.59010849, ..., -0.53177249,
        -0.24941505, -0.26652738],
       [ 0.75277586, -1.67935814,  0.87352491, ..., -0.53177249,
        -0.24941505, -0.26652738]])

In [24]:
from tensorflow.keras.layers import Subtract,Dense,Input,Concatenate
from tensorflow.keras.models import Sequential

In [38]:
X_train.shape

(37497, 84)

In [39]:
model = Sequential()

model.add(Dense(32,activation = 'relu',input_shape = [len(X.keys())] ))
model.add(Dense(64,activation = 'relu' ))
model.add(Dense(1 ))

In [40]:
model.compile(loss= tf.keras.losses.MeanAbsolutePercentageError(),
              optimizer='adam',
              metrics=['mape'])

In [41]:
model.fit(X_train,y_train, validation_split = 0.2,batch_size=16,epochs=5,verbose=1)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 7.3216 - mape: 7.3216 - val_loss: 3.2642 - val_mape: 3.2642
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 2.7364 - mape: 2.7364 - val_loss: 2.5947 - val_mape: 2.5947
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 2.2782 - mape: 2.2782 - val_loss: 2.2232 - val_mape: 2.2232
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 2.1062 - mape: 2.1062 - val_loss: 2.1145 - val_mape: 2.1145
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 1.9843 - mape: 1.9843 - val_loss: 1.9127 - val_mape: 1.9127


In [ ]:
input_tensor = keras.layers.Input(shape = (1,))

In [ ]:
source_input = keras.layers.Input(shape = (1,),name = 'source_state_layer')
source_input = keras.layers.Input(shape = (1,),name = 'destination_state_layer')

Since your model has two inputs now, you need to pass the input data as a list.

In [ ]:
price_diff = Subtract()([source_tensor,destination_tensor])

### Model stacking

In [7]:
target = ubaar.price
features = ubaar[['distanceKM','taxiDurationMin','weight']]
ubaar_tfds = tf.data.Dataset.from_tensor_slices((features.values,target.values))

In [8]:
for sample,target in ubaar_tfds.take(3):
    print(sample,target)

tf.Tensor([1092.  751.   20.], shape=(3,), dtype=float64) tf.Tensor(15300000, shape=(), dtype=int64)
tf.Tensor([414.  264.    2.5], shape=(3,), dtype=float64) tf.Tensor(1800000, shape=(), dtype=int64)
tf.Tensor([310.   292.    14.97], shape=(3,), dtype=float64) tf.Tensor(3742000, shape=(), dtype=int64)


In [11]:
numerical_features = ['distanceKM','taxiDurationMin','weight']
features = []
for  feature in numerical_features:
    col = tf.feature_column.numeric_column(feature)
    features.append(tf.feature_column.indicator_column(col))

ValueError: Unsupported input type. Input must be a CategoricalColumn. Given: NumericColumn(key='distanceKM', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)